[project]
name = "a2d-snapx"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "paramiko>=3.5.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
    "uv>=0.6.14",
]

[tool.ruff]
line-length = 120